### ISSUE TITLE
Support CamelCase types and field names

### ISSUE THREAD

**Issue by devurandom** [oliyh/locksmith#6]
It seems not uncommon in the GraphQL community to use `camelCase` for field names or `CamelCase` for types (see e.g. https://graphql.github.io/learn/queries/ and https://graphql.github.io/learn/schema/). Will this be supported in locksmith as another option and alternative to `snake_keys`?

**Comment by oliyh** [comment]
Hi,

Yes that is a perfectly reasonable feature, I am a bit surprised at myself for only implementing this for snake keys. It may need a bit of work though!
