### ISSUE TITLE
Support UPPERCASE enums

### ISSUE THREAD

**Issue by devurandom** [oliyh/locksmith#7]
It seems not uncommon in the GraphQL community to use `UPPERCASE` for enumeration types (see e.g. https://graphql.github.io/learn/schema/#enumeration-types). Will this be supported in locksmith as another option and alternative to `snake_keys`?

**Comment by oliyh** [comment]
Hi,

I agree that this should work.

**Comment by oliyh** [comment]
It does already support this, with the caveat that the clojure form will be all lowercase (as `(->kebab-case "FOO")` is `"foo"`).

If this is the convention that camel-snake-kebab takes then I think I would prefer to stick with this.
